[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "numpy",
    "scipy",
    "pytorch-fid",
    "torch",
    "scikit-image",
    "matplotlib",
    "torchxrayvision",
    "torchvision",
    "sklearn",
    "tqdm",
]
build-backend = "setuptools.build_meta"
